services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: streamer-chess-mediamtx
    ports:
      - "1935:1935"    # RTMP input
      - "8554:8554"    # RTSP output
      - "8889:8889"    # WebRTC
      - "8890:8890/udp" # WebRTC
    # environment variables can go here if needed
    restart: unless-stopped
    # Optional: mount config file for custom settings
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamer-chess-backend
    depends_on:
      - mediamtx
    environment:
      - ENV=development
      # MediaMTX connection settings for video analysis
      - MEDIAMTX_RTSP_URL=rtsp://mediamtx:8554/live/stream1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["./start.sh"]

